name: e_commerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1
#----------------- Packages -------------------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.5.0
  lottie: ^3.3.1
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #State Management
  get_storage: ^2.1.1
  get: ^4.7.2

  #Product Specific
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

# ----------------- Packages End ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #-------------- Local Assets -----------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/banners/
    - assets/images/animations/
    - assets/images/products/
    - assets/images/account_creation/
    - assets/images/verify_email/
    - assets/images/splash_images/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payments/
    - assets/logos/
    - assets/images/user/

  #-----------Local Fonts ---------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
