name: e_commerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1
#----------------- Packages -------------------------#
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  
  #State Management
  get_storage: ^2.1.1
  get: ^4.7.2

  #Product Specific

# ----------------- Packages End ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #-------------- Local Assets -----------------#
  assets:
    - assets/images/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/logos/

  #-----------Local Fonts ---------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - weight: 400
        - style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
        - weight: 300
        - style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - weight: 300
        - style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - weight: 300
        - style: italic
        - asset: assets/fonts/Poppins-Light.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - weight: 300
        - style: italic
