// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEp4VOChrrqUmMBnKOwgBOshk4i5Q10Ro',
    appId: '1:110016157946:web:5b567b470e25130a52d143',
    messagingSenderId: '110016157946',
    projectId: 'my-e-commerce-applicatio-6a456',
    authDomain: 'my-e-commerce-applicatio-6a456.firebaseapp.com',
    storageBucket: 'my-e-commerce-applicatio-6a456.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAffwPVV9Q6m9RQ2cOacNeA_qHXq0n15Tc',
    appId: '1:110016157946:android:ec81eb82247c5c4052d143',
    messagingSenderId: '110016157946',
    projectId: 'my-e-commerce-applicatio-6a456',
    storageBucket: 'my-e-commerce-applicatio-6a456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhXli_w6S1un6-XEHouol0anPVshWZKxc',
    appId: '1:110016157946:ios:11b4316b2e6b52f952d143',
    messagingSenderId: '110016157946',
    projectId: 'my-e-commerce-applicatio-6a456',
    storageBucket: 'my-e-commerce-applicatio-6a456.firebasestorage.app',
    androidClientId: '110016157946-j9n3d2o3f5crald9q8kt8l9918djcnur.apps.googleusercontent.com',
    iosClientId: '110016157946-cvbdi93oop0900f6ioukldua0f5q2gie.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}